### ISSUE TITLE
Comparing n1-standard-1 to g4dn.xlarge and other issues

### ISSUE THREAD

**Issue by adrian-a-graham** [piercefreeman/cloud-gpu-reliability#4]
Disclosure: I work for Google and do a lot of stuff with GPUs. These are my observations, and don't represent the official position of Google...

Hey @piercefreeman, regarding your results in your [blog post](https://freeman.vc/notes/aws-vs-gcp-reliability-is-wildly-different), I don't think the comparison is accurate for a few reasons.

**Compare similar machine types**
The configs `n1-standard-1` (GCP) and `g4dn.xlarge` (AWS) are not accurate comparisons, here are my thoughts:
    - There's a lot of factors that go into provisioning a VM, but bin-packing machines of different sizes may produce different results. There are policies that Google Cloud can't disclose, but I'd recommend changing the VM shape on GCP to an n1-standard-4 to more closely match the g4dn.xlarge.
    - Boot times can be affected by the number of vCPUs assigned to a VM, including OS initialization and network bandwidth. Google Cloud restricts egress bandwidth depending on number of vCPUs (see [this doc](https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines)), so a n1-standard-1 is fairly limited.
    - Limiting the VM to a single vCPU can severely hinder boot times; I bet if you ran this same test on non-GPU VMs you'd find similar results.

**Select all zones, not just us-central1-b**
It seems you limit your tests to a single zone on Google Cloud, yet have the entire `us-east-1` region on AWS at your disposal. On Google Cloud, GPUs are spread across multiple zones in us-central1; I'd recommend you randomize across zones a, b, c, and f in that region.

**About those 409 Conflict errors**
You're right in that these `409 Conflict` errors probably weren't related to capacity or resource quota. The error could have to do with request rate limiting or just too many concurrent requests (see [this doc](https://cloud.google.com/resource-manager/docs/core_errors#CONFLICT)). You might want to ensure your calls are being performed asynchronously.

**Comment by piercefreeman** [comment]
Thanks for the issue @adrian-a-graham. Keen to try and make this test as fair as possible so appreciate the perspective, especially about the bin packing. Seem like easy enough items to address - let me put up a PR and shoot it by you for a sanity check.

**Comment by akramer** [comment]
Wait, don't re-run yet! :)

I still have one more PR to send. Our client library's operation polling uses a... suboptimal retry strategy. It looks like much of the variance is due to this. I'll send a PR to fix the retry strategy in this code and have raised an internal bug to fix the client library more generally.

**Comment by adrian-a-graham** [comment]
After digging a bit more into the AWS instance type, I _think_ (I'm no AWS expert) that the default disk type on the g4dn's is SSD, whereas you specify `pd-standard` for the Google Cloud VM. Booting will happen much faster if you use `pd-ssd` type disk.

Also, and I'm not sure this affects boot time, your image family should be `ubuntu-2204-lts`, not `ubuntu-2204-lts-arm`. The N1's use Intel-based CPUs, and the base family is for x86 architectures. Unsure if this affects boot time -- maybe there's a bunch of errors/timeouts during the boot process?

**Comment by akramer** [comment]
This benchmark isn't measuring boot time, which makes the instance size/shape/PD type less relevant. An ARM image won't boot on an x86 machine - proof that we're comparing control plane and VM setup times, and not the guest. I do not believe that changing instance types or image family will make any difference in GCE's performance in this test.

**Comment by akramer** [comment]
Okay, pull requests sent, including one to pick a GCE image that can boot on the VM type selected.

**Comment by piercefreeman** [comment]
@adrian-a-graham Just put up a PR to address your remaining suggestions. Like @akramer mentioned, I don't believe the SSD will materially affect the results here but I'm including it to be comprehensive. Linked [here](https://github.com/piercefreeman/cloud-gpu-reliability/pull/9).

> Select all zones, not just us-central1-b
>
> It seems you limit your tests to a single zone on Google Cloud, yet have the entire us-east-1 region on AWS at your disposal. On Google Cloud, GPUs are spread across multiple zones in us-central1; I'd recommend you randomize across zones a, b, c, and f in that region.

On this point I'd push back. GCP doesn't give you an option to spawn a VM tied to a region whereas AWS does. From the consumer layer we do have to choose which availability zone to spin a new VM up in, which is the behavior that the test implements. If there's cloud specific tooling that makes background choices to optimize resource availability (which perhaps AWS is doing), I believe that's a valid part of the comparison.

If I'm missing an element of the GCP API here that lets you provision into the region please let me know.
